"""DPoP (RFC 9449) proof-of-possession JWTs for sender-constraining OAuth tokens.

Distinct from the OIDC4VCI `jwt` proof type generated by a `WalletAdapter`: DPoP binds the
*access token* to a key at the OAuth layer, independent of whichever key the eventual
credential is bound to. A DPoP key is generated per issuance session and intentionally does
not go through the WalletAdapter boundary — it protects this session's OAuth exchange, not
the holder's long-term credential-binding key.
"""

import hashlib
import json
import time
import uuid
from urllib.parse import urlsplit, urlunsplit

import jwt
from cryptography.hazmat.primitives.asymmetric import ec
from jwt.algorithms import ECAlgorithm
from jwt.utils import base64url_encode

DPOP_JWT_TYPE = "dpop+jwt"

# The only DPoP signing algorithm this implementation supports, matching the only algorithm
# MockWalletAdapter signs credential-binding proofs with.
SUPPORTED_DPOP_SIGNING_ALG = "ES256"


class DPoPKey:
    """A per-session EC keypair used to sign DPoP proofs (spec §4)."""

    def __init__(self) -> None:
        self._private_key = ec.generate_private_key(ec.SECP256R1())

    def create_proof(
        self,
        *,
        http_method: str,
        http_uri: str,
        nonce: str | None = None,
        access_token: str | None = None,
    ) -> str:
        """Build one DPoP proof JWT (spec §4.2) for a single HTTP request.

        `access_token` sets the `ath` claim (spec §4.2, required when presenting a
        DPoP-bound access token to a protected resource) — omit it for the token request
        itself, where no access token exists yet.
        """
        claims: dict[str, object] = {
            "jti": str(uuid.uuid4()),
            "htm": http_method,
            "htu": _without_query_and_fragment(http_uri),
            "iat": int(time.time()),
        }
        if nonce is not None:
            claims["nonce"] = nonce
        if access_token is not None:
            claims["ath"] = base64url_encode(
                hashlib.sha256(access_token.encode("ascii")).digest()
            ).decode()

        public_jwk = json.loads(
            ECAlgorithm(ECAlgorithm.SHA256).to_jwk(self._private_key.public_key())
        )
        return jwt.encode(
            claims,
            self._private_key,
            algorithm=SUPPORTED_DPOP_SIGNING_ALG,
            headers={"typ": DPOP_JWT_TYPE, "jwk": public_jwk},
        )


def _without_query_and_fragment(uri: str) -> str:
    parts = urlsplit(uri)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))
